# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# flooding.py
# Created on: 2020-10-16 11:17:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Name: Jess Strzempko 
# Python Version: 2.7.15
# Assignment: Lab 1 Geoprocessing in ArcGIS
# Description: This script clips the flood zones layer to the basin boundaries. It then selects areas that are within the Special Hazard Flood Area.
# It was created as Exercise 1 in Lab 1 Geoprocessing in ArcGIS for IDCE 30274 Computer Programming for GIS. 
# Inputs: floodzones.shp [layer of flood zones], basin.shp [basin boundaries]
# Outputs: flood_Clip.shp [intermediary layer of flood zones clipped to basin], flooding.shp [final layer of areas in basin and high risk flood zones]
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
floodzones_shp = "C:\\Users\\JeStrzempko\\Documents\\Comp_Prog\\Lab1\\Data_Lab_1_Geoprocessing_ArcGIS\\Data_Lab_1_Geoprocessing_ArcGIS\\floodzones.shp"
basin_shp = "C:\\Users\\JeStrzempko\\Documents\\Comp_Prog\\Lab1\\Data_Lab_1_Geoprocessing_ArcGIS\\Data_Lab_1_Geoprocessing_ArcGIS\\basin.shp"
flood_Clip_shp = "C:\\Users\\JeStrzempko\\Documents\\Comp_Prog\\Lab1\\Data_Lab_1_Geoprocessing_ArcGIS\\Results\\flood_Clip.shp"
flooding_shp = "C:\\Users\\JeStrzempko\\Documents\\Comp_Prog\\Lab1\\Data_Lab_1_Geoprocessing_ArcGIS\\Results\\flooding.shp"

# Process: Clip
arcpy.Clip_analysis(floodzones_shp, basin_shp, flood_Clip_shp, "")

# Process: Select
arcpy.Select_analysis(flood_Clip_shp, flooding_shp, "\"SFHA\" = 'IN'")


Leave the lines of comment code, above, but add your personal details. Then replace these two lines of code with your new code! 
